### ISSUE TITLE
ERR_SETFILECOUNT_LARGERONE

### ISSUE THREAD

**Issue by KirbyKFC** [mhvuze/GEUndub#3]
I saw many errors like ”ERR_SETFILECOUNT_LARGERONE,qpck 50,set 1“.
After I deleted the code and did a test.
```
// DELETE
/*
if (count_set_files > 1)
{
    debuglog.WriteLine("ERR_SETFILECOUNT_LARGERONE,qpck {0},set {1}", (i + 1), (j + 1));
    break;
}
*/
```
I saw these messages.
MSG_FILE_REPLACED,qpck 50,set 1,file 1,btl_pc14m_Step.is14
MSG_FILE_REPLACED,qpck 50,set 1,file 2,btl_pc14m_Jump.is14
MSG_FILE_REPLACED,qpck 50,set 1,file 3,btl_pc14m_Strain.is14
MSG_FILE_REPLACED,qpck 50,set 1,file 4,btl_pc14m_CloseAttack_S_1.is14
MSG_FILE_REPLACED,qpck 50,set 1,file 5,btl_pc14m_CloseAttack_S_2.is14
MSG_FILE_REPLACED,qpck 50,set 1,file 6,btl_pc14m_CloseAttack_S_3.is14
ERR_FILE_MISSING,qpck 50,set 1,file 7,btl_pc14m_CloseAttack_B_1.is14
ERR_FILE_MISSING,qpck 50,set 1,file 8,btl_pc14m_CloseAttack_B_2.is14
......
ERR_FILE_MISSING,qpck 50,set 1,file 83,btl_pc14m_BR_Phase3_BA_ComboAttack_2.is14

So
1. Seems that it can't replace these files at present.
2. According to those "ERR_FILE_MISSING", I didn't get all the audio files by quickbms (with God Eater 2 script 0.2.2). Wondering how to find the rest files.

**Comment by Crashdummyy** [comment]
Did you get it to work ?
I don't know where to start.
From where did you start building it ? ( I can't start it to begin with, only when i started hardcoding the Paths )

Do You have the "res" folder ? It seems its missing for me, whats inside ?
