### ISSUE TITLE
Where to get *.is14 files ?

### ISSUE THREAD

**Issue by Crashdummyy** [mhvuze/GEUndub#4]
Hey there.
I want to get rid of the crappy english voices.
Well there are two problems:
- I don't have the **res** folder
- The log file tells me it can't find the files inside the *.qpck

Need Help :)

EDIT: Comparing with the released GERB undub I see that i need to get the correct .is14 voice files.
Where do I get them ?

**Comment by mhvuze** [comment]
If I recall correctly, these files were ripped from the PSVita version of the game and sent to me. I don't have them on my PC anymore and this tool was merely an attempt to undub the game but I eventually stopped bothering with it for various reasons.

**Comment by Crashdummyy** [comment]
Thanks for the reply :)
Well I do have the vita undub files ( got it through wololo Thread ).
Inside the archive there are several folders ( data_0 to data_f ) each containing some *.nus3bank files.

Did you convert (extract?) them to be the needed *.is14 ?

**Comment by Crashdummyy** [comment]
Okay I am somehow able to extract the idsp files, but which format is needed ? 
wav? idsp? is14?
